### ISSUE TITLE
How can I add Spawners?

### ISSUE THREAD

**Issue by fede-pe02** [itsnewtjam/newtShop-Issues#23]
I’ve already created the category for them, but when I write everything down on the .yml file, they just don’t show up when I type /shop in-game.
![image](https://user-images.githubusercontent.com/63166029/78459236-fcaec580-768d-11ea-8d65-f963b63db737.jpg)
(I tried this way and it doesn’t work. Ignore the other spawners because I already know that the material type is invalid in the other cases) Use as example of what I did the chicken one. I need help with this, please.

**Comment by itsnewtjam** [comment]
Since spawners tend to have pretty varying data tied to them depending on spawner plugins and whatnot, there's no preset way to add them in. However, you can still add them as special items by using the [/shopmanage command](https://docs.newtjam.com/newtshop/commands/#shopmanage-add-category62-item_name62-buy62-sell62-91slot-91title).

In your case for the chicken one, you would simply hold the spawner in game and run `/shopmanage add spawners CHICKEN 120000 1 none Chicken Spawner` for example.

Let me know if you need any further help!
