### ISSUE TITLE
Some useful features

### ISSUE THREAD

**Issue by dustindinh** [itsnewtjam/newtShop-Issues#3]
** Add reload commands to reload change from config

** Add open shop for player from console.

** More config about GUI like decorations gui, run command button , . . .

**  Thank you :D

**Comment by itsnewtjam** [comment]
I actually was just working on the reload command, that'll be in the next update! I'll also go ahead and add in opening from console as well.

Could you elaborate on the more config you're looking for?

**Comment by dustindinh** [comment]
I mean the more config is like every custom GUI plugins (bosshop, deluxemenu, . . .) we can define item, what going on when click it, slot , . . .

**Comment by itsnewtjam** [comment]
Custom slots were just added in v1.3.1, can now use the 'customSlot' option in category .yml files to set a specific slot in the category's item list.

Command items were added in v1.2.0, you can see how to define them in the docs [here](https://docs.newtjam.com/newtshop/category-files/#command-item-options)! Let me know if you need any additional help with setting those up.
__Note:__ As of v1.3.0 you can also use the '/shopmanage add' command to directly add a custom item (spawners, crate keys, etc) to the shop rather than using command items. You can see the guide to the command [here](https://docs.newtjam.com/newtshop/commands/#shopmanage-add-category62-item_name62-buy62-sell62-91slot-91title). Again, let me know if you need any additional help.

I'll close this issue for now, but if you have any other specific requests in the future feel free to open another!
